name: CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Check imports with `isort`
      run: |
        isort --check-only .
    - name: Check formatting with `black`
      run: |
        black --check .
    - name: Lint with `flake8`
      run: |
        flake8 .
    - name: Check code security with `bandit`
      run: |
        bandit -r . -lll -iii
    - name: Check dependency security with `safety`
      run: |
        safety check --full-report --file=requirements.txt
    - name: Check type safety with `mypy`
      run: |
        mypy .
    - name: Run tests with pytest
      run: |
        pytest tests --cov --cov-fail-under=90
